### PR TITLE
finite difference with python

### PR DESCRIPTION
**Pull request by alifele**
I translated the code for the finite difference method you wrote in Julia to Python.

### CODE REVIEW

**Comment by alifele** [comment]
python implementation for finite difference

**Comment by cortner** [comment]
thank you for this initiative! Would you be willing to do an nbstripout on the notebook? I sometimes forget this myself but as a general rule I like to avoid having the outputs in the git repo.

**Comment by cortner** [comment]
and maybe a second suggestion : can you move the notebook to a subfolder `python`. I'll think about moving my own notebooks into another subfolder `julia`...

**Comment by alifele** [comment]
I made the changes as you requested.

**Comment by cortner** [comment]
thank you!

**Pull request merged**
